#!/bin/ksh
echo " +---------------------------------------------------------------------------------------------------------+"
echo " |                            Powered by the AUTOMATED CODE MIGRATION TOOL.                                |  "
echo " | If you face any issues or have any brickbats for this tool please contact ERP WICER Team                |  "
echo " |                             Generated by Template Version 14                                           |  "
echo " +---------------------------------------------------------------------------------------------------------+"
#/*
#||   Filename: ROTC85_INSTALL.sh
#||   Description: Commercial Invoice Report
#||   Ver       Date           Author           Modification
#||   1.0       7/10/2019      Ritika Trivedi   Initial Creation
#||
#||   Usage : Install the object 'Commercial Invoice Report'
#||
#||   Copyright Gilead
#||   ****************
#||   All rights reserved.
#*/
INSTALLATION_LOGFILE=$0.`date +%d%b%y_%H%M%S`.log
# *******************************************************************
#  Function to copy file on remote DMZ server
# *******************************************************************
COPY_TO_DMZ(){
echo  ".....Copying to remote server: $XXGIL_EXTERNAL_SERVER "
if [ -z "$XXGIL_EXTERNAL_SERVER" ]; then
    echo ".....[WARNING]:External server variable XXGIL_EXTERNAL_SERVER not set. File $1 will not be copied to any remote server."
else 
     echo ".....Copying $1 to remote server $XXGIL_EXTERNAL_SERVER"
     scp $1 ${XXGIL_EXTERNAL_SERVER}:$2/$1 
     ssh ${XXGIL_EXTERNAL_SERVER} chmod 755 $2/$1
fi
}

# *******************************************************************
#  Function to create soft link on remote DMZ server
# *******************************************************************
LINK_IN_DMZ(){
echo "....Creating link in remote server: $XXGIL_EXTERNAL_SERVER "
if [ -z "$XXGIL_EXTERNAL_SERVER" ]; then
    echo "....[WARNING]:External server variable XXGIL_EXTERNAL_SERVER not set. link will not be created on any remote server."
else
     echo ".....Creating link $1 on $XXGIL_EXTERNAL_SERVER"
     ssh  ${XXGIL_EXTERNAL_SERVER} ln -sf $1 $2
fi
}

# *******************************************************************
#  Function to Check the validity of login ids and password.
# *******************************************************************
CHKLOGIN(){
if sqlplus -s /nolog <<! >/dev/null 2>&1
WHENEVER SQLERROR EXIT 1;
CONNECT $1 ;
 
EXIT
!
then
echo OK
else
echo NOK
fi
}



# *******************************************************************
#  Main function
# *******************************************************************
MAIN(){
echo "---------------------[Start of Installation]---------------------"
echo "Process Started at `date +%d/%m/%y.%H:%M:%S`"
echo "SVN Repository Path: http://fcsource01:8080/svn/WICER/ROTC85/"
echo "Installation logfile: $INSTALLATION_LOGFILE "
echo " "
migrErrorCode=0 

# *******************************************************************
#  Prompt for APPS Login Id /Password
# *******************************************************************
echo  "-----------------------[EBS Database Login]-----------------------"
while [ "$APPSID" = "" -o `CHKLOGIN "$APPSID"` = "NOK" ]
do
if [ "$APPSID" = "" ];then
echo "Enter APPS Login Userid/Passwd (entered text will not display): "
read -s APPSID
else
echo " APPS Login UserId And Password Is Not CORRECT "
APPSID=""
fi
done    

# *******************************************************************
#  Prompt for SVN Login Id /Password
# *******************************************************************
SUBVERSION_UserName=SVNWERACCT
SVN_Password=svnwer123
while [ "$SUBVERSION_UserName" = "" -o "$SVN_Password" = "" ]
do
echo  "----------------------------[SVN Login]---------------------------"
echo "   Enter SVN Userid : "
read SUBVERSION_UserName
echo "   Enter SVN (Gilead SSO) Password (entered text will not display) : "
read -s SVN_Password
done    
echo  " Removing the existing WICER ROTC85_122 Directory "
rm -rf ROTC85_122
 
echo  "+---------------------------------------------------------------------+"
echo  "| Checking out files for WICER: ROTC85_122                       "
echo  "+---------------------------------------------------------------------+"
 
/opt/CollabNet_Subversion/bin/svn co --username $SUBVERSION_UserName  --password $SVN_Password  --depth empty  http://fcsource01:8080/svn/WICER/ROTC85/ROTC85_122
cd ROTC85_122
 
/opt/CollabNet_Subversion/bin/svn up -r 48959 XXGIL_RA_INT_LINES_ALL_T1.trg
if [ -e XXGIL_RA_INT_LINES_ALL_T1.trg ]; then
  echo "XXGIL_RA_INT_LINES_ALL_T1.trg checked out successfully."
else
  echo "[ERROR]: XXGIL_RA_INT_LINES_ALL_T1.trg FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 62164 XXGILARCOMINVSPLIT.rdf
if [ -e XXGILARCOMINVSPLIT.rdf ]; then
  echo "XXGILARCOMINVSPLIT.rdf checked out successfully."
else
  echo "[ERROR]: XXGILARCOMINVSPLIT.rdf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 48666 AUSTRALIA.rtf
if [ -e AUSTRALIA.rtf ]; then
  echo "AUSTRALIA.rtf checked out successfully."
else
  echo "[ERROR]: AUSTRALIA.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 48666 KOREA.rtf
if [ -e KOREA.rtf ]; then
  echo "KOREA.rtf checked out successfully."
else
  echo "[ERROR]: KOREA.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 48666 NETHERLANDS.rtf
if [ -e NETHERLANDS.rtf ]; then
  echo "NETHERLANDS.rtf checked out successfully."
else
  echo "[ERROR]: NETHERLANDS.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 48666 NEWZELAND.rtf
if [ -e NEWZELAND.rtf ]; then
  echo "NEWZELAND.rtf checked out successfully."
else
  echo "[ERROR]: NEWZELAND.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 48666 NORWAY.rtf
if [ -e NORWAY.rtf ]; then
  echo "NORWAY.rtf checked out successfully."
else
  echo "[ERROR]: NORWAY.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 48666 POLAND.rtf
if [ -e POLAND.rtf ]; then
  echo "POLAND.rtf checked out successfully."
else
  echo "[ERROR]: POLAND.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 48666 PORTUGAL.rtf
if [ -e PORTUGAL.rtf ]; then
  echo "PORTUGAL.rtf checked out successfully."
else
  echo "[ERROR]: PORTUGAL.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 48666 SPAIN.rtf
if [ -e SPAIN.rtf ]; then
  echo "SPAIN.rtf checked out successfully."
else
  echo "[ERROR]: SPAIN.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 48666 SWEDEN.rtf
if [ -e SWEDEN.rtf ]; then
  echo "SWEDEN.rtf checked out successfully."
else
  echo "[ERROR]: SWEDEN.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 48666 UK.rtf
if [ -e UK.rtf ]; then
  echo "UK.rtf checked out successfully."
else
  echo "[ERROR]: UK.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 48666 JAPAN.rtf
if [ -e JAPAN.rtf ]; then
  echo "JAPAN.rtf checked out successfully."
else
  echo "[ERROR]: JAPAN.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 50030 HONGKONG.rtf
if [ -e HONGKONG.rtf ]; then
  echo "HONGKONG.rtf checked out successfully."
else
  echo "[ERROR]: HONGKONG.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 48666 BELGIUM.rtf
if [ -e BELGIUM.rtf ]; then
  echo "BELGIUM.rtf checked out successfully."
else
  echo "[ERROR]: BELGIUM.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 48666 DENMARK.rtf
if [ -e DENMARK.rtf ]; then
  echo "DENMARK.rtf checked out successfully."
else
  echo "[ERROR]: DENMARK.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 48666 FINLAND.rtf
if [ -e FINLAND.rtf ]; then
  echo "FINLAND.rtf checked out successfully."
else
  echo "[ERROR]: FINLAND.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 58595 IRELAND.rtf
if [ -e IRELAND.rtf ]; then
  echo "IRELAND.rtf checked out successfully."
else
  echo "[ERROR]: IRELAND.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 48666 CANADA.rtf
if [ -e CANADA.rtf ]; then
  echo "CANADA.rtf checked out successfully."
else
  echo "[ERROR]: CANADA.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 51142 USA.rtf
if [ -e USA.rtf ]; then
  echo "USA.rtf checked out successfully."
else
  echo "[ERROR]: USA.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 48666 BELGIUM.rtf
if [ -e BELGIUM.rtf ]; then
  echo "BELGIUM.rtf checked out successfully."
else
  echo "[ERROR]: BELGIUM.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 48666 DENMARK.rtf
if [ -e DENMARK.rtf ]; then
  echo "DENMARK.rtf checked out successfully."
else
  echo "[ERROR]: DENMARK.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 48666 FINLAND.rtf
if [ -e FINLAND.rtf ]; then
  echo "FINLAND.rtf checked out successfully."
else
  echo "[ERROR]: FINLAND.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 58595 IRELAND.rtf
if [ -e IRELAND.rtf ]; then
  echo "IRELAND.rtf checked out successfully."
else
  echo "[ERROR]: IRELAND.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 48666 NETHERLANDS.rtf
if [ -e NETHERLANDS.rtf ]; then
  echo "NETHERLANDS.rtf checked out successfully."
else
  echo "[ERROR]: NETHERLANDS.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 48666 NORWAY.rtf
if [ -e NORWAY.rtf ]; then
  echo "NORWAY.rtf checked out successfully."
else
  echo "[ERROR]: NORWAY.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 48666 SPAIN.rtf
if [ -e SPAIN.rtf ]; then
  echo "SPAIN.rtf checked out successfully."
else
  echo "[ERROR]: SPAIN.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 48666 SWEDEN.rtf
if [ -e SWEDEN.rtf ]; then
  echo "SWEDEN.rtf checked out successfully."
else
  echo "[ERROR]: SWEDEN.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 51142 USA.rtf
if [ -e USA.rtf ]; then
  echo "USA.rtf checked out successfully."
else
  echo "[ERROR]: USA.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 48669 TAIWAN.rtf
if [ -e TAIWAN.rtf ]; then
  echo "TAIWAN.rtf checked out successfully."
else
  echo "[ERROR]: TAIWAN.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 50030 SINGAPORE.rtf
if [ -e SINGAPORE.rtf ]; then
  echo "SINGAPORE.rtf checked out successfully."
else
  echo "[ERROR]: SINGAPORE.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 48666 AUSTRIA.rtf
if [ -e AUSTRIA.rtf ]; then
  echo "AUSTRIA.rtf checked out successfully."
else
  echo "[ERROR]: AUSTRIA.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 62122 FRANCE.rtf
if [ -e FRANCE.rtf ]; then
  echo "FRANCE.rtf checked out successfully."
else
  echo "[ERROR]: FRANCE.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 50030 GERMANY.rtf
if [ -e GERMANY.rtf ]; then
  echo "GERMANY.rtf checked out successfully."
else
  echo "[ERROR]: GERMANY.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 48666 ITALY.rtf
if [ -e ITALY.rtf ]; then
  echo "ITALY.rtf checked out successfully."
else
  echo "[ERROR]: ITALY.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 48666 SWITZERLAND.rtf
if [ -e SWITZERLAND.rtf ]; then
  echo "SWITZERLAND.rtf checked out successfully."
else
  echo "[ERROR]: SWITZERLAND.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 50030 GREECE.rtf
if [ -e GREECE.rtf ]; then
  echo "GREECE.rtf checked out successfully."
else
  echo "[ERROR]: GREECE.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 51142 USA.rtf
if [ -e USA.rtf ]; then
  echo "USA.rtf checked out successfully."
else
  echo "[ERROR]: USA.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 58595 IRELAND.rtf
if [ -e IRELAND.rtf ]; then
  echo "IRELAND.rtf checked out successfully."
else
  echo "[ERROR]: IRELAND.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 48666 NETHERLANDS.rtf
if [ -e NETHERLANDS.rtf ]; then
  echo "NETHERLANDS.rtf checked out successfully."
else
  echo "[ERROR]: NETHERLANDS.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 48666 NEWZELAND.rtf
if [ -e NEWZELAND.rtf ]; then
  echo "NEWZELAND.rtf checked out successfully."
else
  echo "[ERROR]: NEWZELAND.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 48666 NORWAY.rtf
if [ -e NORWAY.rtf ]; then
  echo "NORWAY.rtf checked out successfully."
else
  echo "[ERROR]: NORWAY.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 48666 PORTUGAL.rtf
if [ -e PORTUGAL.rtf ]; then
  echo "PORTUGAL.rtf checked out successfully."
else
  echo "[ERROR]: PORTUGAL.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 48666 SPAIN.rtf
if [ -e SPAIN.rtf ]; then
  echo "SPAIN.rtf checked out successfully."
else
  echo "[ERROR]: SPAIN.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 48666 SWEDEN.rtf
if [ -e SWEDEN.rtf ]; then
  echo "SWEDEN.rtf checked out successfully."
else
  echo "[ERROR]: SWEDEN.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 48666 UK.rtf
if [ -e UK.rtf ]; then
  echo "UK.rtf checked out successfully."
else
  echo "[ERROR]: UK.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 48666 AUSTRALIA.rtf
if [ -e AUSTRALIA.rtf ]; then
  echo "AUSTRALIA.rtf checked out successfully."
else
  echo "[ERROR]: AUSTRALIA.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 48666 BELGIUM.rtf
if [ -e BELGIUM.rtf ]; then
  echo "BELGIUM.rtf checked out successfully."
else
  echo "[ERROR]: BELGIUM.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 48666 DENMARK.rtf
if [ -e DENMARK.rtf ]; then
  echo "DENMARK.rtf checked out successfully."
else
  echo "[ERROR]: DENMARK.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 48666 FINLAND.rtf
if [ -e FINLAND.rtf ]; then
  echo "FINLAND.rtf checked out successfully."
else
  echo "[ERROR]: FINLAND.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 48666 CANADA.rtf
if [ -e CANADA.rtf ]; then
  echo "CANADA.rtf checked out successfully."
else
  echo "[ERROR]: CANADA.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 48666 GERMANY.rtf
if [ -e GERMANY.rtf ]; then
  echo "GERMANY.rtf checked out successfully."
else
  echo "[ERROR]: GERMANY.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 62122 FRANCE.rtf
if [ -e FRANCE.rtf ]; then
  echo "FRANCE.rtf checked out successfully."
else
  echo "[ERROR]: FRANCE.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 48666 SWITZERLAND.rtf
if [ -e SWITZERLAND.rtf ]; then
  echo "SWITZERLAND.rtf checked out successfully."
else
  echo "[ERROR]: SWITZERLAND.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 48666 AUSTRIA.rtf
if [ -e AUSTRIA.rtf ]; then
  echo "AUSTRIA.rtf checked out successfully."
else
  echo "[ERROR]: AUSTRIA.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 48666 ITALY.rtf
if [ -e ITALY.rtf ]; then
  echo "ITALY.rtf checked out successfully."
else
  echo "[ERROR]: ITALY.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 48666 SPAIN.rtf
if [ -e SPAIN.rtf ]; then
  echo "SPAIN.rtf checked out successfully."
else
  echo "[ERROR]: SPAIN.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 48666 SWEDEN.rtf
if [ -e SWEDEN.rtf ]; then
  echo "SWEDEN.rtf checked out successfully."
else
  echo "[ERROR]: SWEDEN.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 46819 XXGIL_EMAIL_COMM_INVOICE_PKG.pkb
if [ -e XXGIL_EMAIL_COMM_INVOICE_PKG.pkb ]; then
  echo "XXGIL_EMAIL_COMM_INVOICE_PKG.pkb checked out successfully."
else
  echo "[ERROR]: XXGIL_EMAIL_COMM_INVOICE_PKG.pkb FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 48985 PORTUGAL_PRINT.rtf
if [ -e PORTUGAL_PRINT.rtf ]; then
  echo "PORTUGAL_PRINT.rtf checked out successfully."
else
  echo "[ERROR]: PORTUGAL_PRINT.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 48666 GERMANY.rtf
if [ -e GERMANY.rtf ]; then
  echo "GERMANY.rtf checked out successfully."
else
  echo "[ERROR]: GERMANY.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 48666 GERMANY.rtf
if [ -e GERMANY.rtf ]; then
  echo "GERMANY.rtf checked out successfully."
else
  echo "[ERROR]: GERMANY.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 48666 AUSTRIA.rtf
if [ -e AUSTRIA.rtf ]; then
  echo "AUSTRIA.rtf checked out successfully."
else
  echo "[ERROR]: AUSTRIA.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 48666 SWITZERLAND.rtf
if [ -e SWITZERLAND.rtf ]; then
  echo "SWITZERLAND.rtf checked out successfully."
else
  echo "[ERROR]: SWITZERLAND.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 62122 FRANCE.rtf
if [ -e FRANCE.rtf ]; then
  echo "FRANCE.rtf checked out successfully."
else
  echo "[ERROR]: FRANCE.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
/opt/CollabNet_Subversion/bin/svn up -r 48666 ITALY.rtf
if [ -e ITALY.rtf ]; then
  echo "ITALY.rtf checked out successfully."
else
  echo "[ERROR]: ITALY.rtf FAILED to check out"
  echo "Fatal Error..."
    migrErrorCode=1 
  #exit
fi
 
cd ..
export FORMS_PATH=$FORMS_PATH:$AU_TOP/forms/US
 apps_user=`echo $APPSID | cut -d / -f 1 | cut -d @ -f 1`
 apps_pwd=`echo $APPSID | cut -d / -f 2 | cut -d @ -f 1`
 DB_HOST=`cat $CONTEXT_FILE |grep s_apps_jdbc_connect_descriptor | sed 's/.*HOST=\(.*\))(PORT.*/\1/g'`
 DB_PORT=`cat $CONTEXT_FILE |grep s_apps_jdbc_connect_descriptor | sed 's/.*PORT=\(.*\))))(CONNECT.*/\1/g'`
 DB_SID=`cat $CONTEXT_FILE |grep s_apps_jdbc_connect_descriptor | sed 's/.*SID=\(.*\)))).*/\1/g'`
 TNS_STRING=`cat $CONTEXT_FILE|grep s_apps_jdbc_connect_descriptor|cut -d @ -f 2 | sed 's/<\/jdbc_url>//'`
cd ROTC85_122
echo  "+---------------------------------------------------------------------+"
echo  "| Compiling and copying files for WICER ROTC85_122 "
echo  "+---------------------------------------------------------------------+"
if [ -e XXGIL_RA_INT_LINES_ALL_T1.trg ]; then
  dos2unix XXGIL_RA_INT_LINES_ALL_T1.trg
  echo ".....Compiling XXGIL_RA_INT_LINES_ALL_T1.trg"
  cp -f XXGIL_RA_INT_LINES_ALL_T1.trg $XXGIL_TOP/sql/
  chmod 755 $XXGIL_TOP/sql/XXGIL_RA_INT_LINES_ALL_T1.trg
  COPY_TO_DMZ  XXGIL_RA_INT_LINES_ALL_T1.trg $XXGIL_TOP/sql/
  sqlplus -s  $APPSID @XXGIL_RA_INT_LINES_ALL_T1.trg > XXGIL_RA_INT_LINES_ALL_T1.trg.log 2> XXGIL_RA_INT_LINES_ALL_T1.trg.log
  errorcount=0
  errorcount=`grep -i error XXGIL_RA_INT_LINES_ALL_T1.trg.log | grep -icv "No errors" | wc -l `
  cat XXGIL_RA_INT_LINES_ALL_T1.trg.log
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e XXGILARCOMINVSPLIT.rdf ]; then
  echo ".....Copying XXGILARCOMINVSPLIT.rdf"
  cp -f XXGILARCOMINVSPLIT.rdf $XXGIL_TOP/reports/US/
    chmod 755 $XXGIL_TOP/reports/US/XXGILARCOMINVSPLIT.rdf
    COPY_TO_DMZ XXGILARCOMINVSPLIT.rdf $XXGIL_TOP/reports/US/
  if [ -e $XXGIL_TOP/reports/US/XXGILARCOMINVSPLIT.rdf ]; then
    migrErrorCode=migrErrorCode 
  else
    migrErrorCode=1 
  fi
fi
if [ -e AUSTRALIA.rtf ]; then
  echo ".....Executing XDOLoader for AUSTRALIA.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINVS_AUSTRALIA \
  -LANGUAGE en \
  -TERRITORY AU \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME AUSTRALIA.rtf \
  -LOG_FILE AUSTRALIA.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat AUSTRALIA.rtf.log 
  errorcount=0
  errorcount=`grep -i error AUSTRALIA.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e KOREA.rtf ]; then
  echo ".....Executing XDOLoader for KOREA.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINVS_KOREA \
  -LANGUAGE en \
  -TERRITORY KR \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME KOREA.rtf \
  -LOG_FILE KOREA.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat KOREA.rtf.log 
  errorcount=0
  errorcount=`grep -i error KOREA.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e NETHERLANDS.rtf ]; then
  echo ".....Executing XDOLoader for NETHERLANDS.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINVS_NETHERLANDS \
  -LANGUAGE nl \
  -TERRITORY NL \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME NETHERLANDS.rtf \
  -LOG_FILE NETHERLANDS.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat NETHERLANDS.rtf.log 
  errorcount=0
  errorcount=`grep -i error NETHERLANDS.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e NEWZELAND.rtf ]; then
  echo ".....Executing XDOLoader for NEWZELAND.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINVS_NEWZELAND \
  -LANGUAGE en \
  -TERRITORY NZ \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME NEWZELAND.rtf \
  -LOG_FILE NEWZELAND.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat NEWZELAND.rtf.log 
  errorcount=0
  errorcount=`grep -i error NEWZELAND.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e NORWAY.rtf ]; then
  echo ".....Executing XDOLoader for NORWAY.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINVS_NORWAY \
  -LANGUAGE no \
  -TERRITORY NO \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME NORWAY.rtf \
  -LOG_FILE NORWAY.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat NORWAY.rtf.log 
  errorcount=0
  errorcount=`grep -i error NORWAY.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e POLAND.rtf ]; then
  echo ".....Executing XDOLoader for POLAND.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINVS_POLAND \
  -LANGUAGE en \
  -TERRITORY PL \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME POLAND.rtf \
  -LOG_FILE POLAND.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat POLAND.rtf.log 
  errorcount=0
  errorcount=`grep -i error POLAND.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e PORTUGAL.rtf ]; then
  echo ".....Executing XDOLoader for PORTUGAL.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINVS_PORTUGAL \
  -LANGUAGE pt \
  -TERRITORY PT \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME PORTUGAL.rtf \
  -LOG_FILE PORTUGAL.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat PORTUGAL.rtf.log 
  errorcount=0
  errorcount=`grep -i error PORTUGAL.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e SPAIN.rtf ]; then
  echo ".....Executing XDOLoader for SPAIN.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINVS_SPAIN \
  -LANGUAGE es \
  -TERRITORY ES \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME SPAIN.rtf \
  -LOG_FILE SPAIN.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat SPAIN.rtf.log 
  errorcount=0
  errorcount=`grep -i error SPAIN.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e SWEDEN.rtf ]; then
  echo ".....Executing XDOLoader for SWEDEN.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINVS_SWEDEN \
  -LANGUAGE sv \
  -TERRITORY SE \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME SWEDEN.rtf \
  -LOG_FILE SWEDEN.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat SWEDEN.rtf.log 
  errorcount=0
  errorcount=`grep -i error SWEDEN.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e UK.rtf ]; then
  echo ".....Executing XDOLoader for UK.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINVS_UK \
  -LANGUAGE en \
  -TERRITORY GB \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME UK.rtf \
  -LOG_FILE UK.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat UK.rtf.log 
  errorcount=0
  errorcount=`grep -i error UK.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e JAPAN.rtf ]; then
  echo ".....Executing XDOLoader for JAPAN.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINVS_JP \
  -LANGUAGE ja \
  -TERRITORY JP \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME JAPAN.rtf \
  -LOG_FILE JAPAN.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat JAPAN.rtf.log 
  errorcount=0
  errorcount=`grep -i error JAPAN.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e HONGKONG.rtf ]; then
  echo ".....Executing XDOLoader for HONGKONG.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINVS_HONGKONG \
  -LANGUAGE en \
  -TERRITORY HK \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME HONGKONG.rtf \
  -LOG_FILE HONGKONG.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat HONGKONG.rtf.log 
  errorcount=0
  errorcount=`grep -i error HONGKONG.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e BELGIUM.rtf ]; then
  echo ".....Executing XDOLoader for BELGIUM.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINVS_BELGIUM \
  -LANGUAGE en \
  -TERRITORY BE \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME BELGIUM.rtf \
  -LOG_FILE BELGIUM.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat BELGIUM.rtf.log 
  errorcount=0
  errorcount=`grep -i error BELGIUM.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e DENMARK.rtf ]; then
  echo ".....Executing XDOLoader for DENMARK.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINVS_DENMARK \
  -LANGUAGE da \
  -TERRITORY DK \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME DENMARK.rtf \
  -LOG_FILE DENMARK.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat DENMARK.rtf.log 
  errorcount=0
  errorcount=`grep -i error DENMARK.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e FINLAND.rtf ]; then
  echo ".....Executing XDOLoader for FINLAND.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINVS_FINLAND \
  -LANGUAGE fi \
  -TERRITORY FI \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME FINLAND.rtf \
  -LOG_FILE FINLAND.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat FINLAND.rtf.log 
  errorcount=0
  errorcount=`grep -i error FINLAND.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e IRELAND.rtf ]; then
  echo ".....Executing XDOLoader for IRELAND.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINVS_IRELAND \
  -LANGUAGE en \
  -TERRITORY IE \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME IRELAND.rtf \
  -LOG_FILE IRELAND.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat IRELAND.rtf.log 
  errorcount=0
  errorcount=`grep -i error IRELAND.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e CANADA.rtf ]; then
  echo ".....Executing XDOLoader for CANADA.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINVS_CANADA \
  -LANGUAGE en \
  -TERRITORY CA \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME CANADA.rtf \
  -LOG_FILE CANADA.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat CANADA.rtf.log 
  errorcount=0
  errorcount=`grep -i error CANADA.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e USA.rtf ]; then
  echo ".....Executing XDOLoader for USA.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINVS_USA \
  -LANGUAGE en \
  -TERRITORY US \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME USA.rtf \
  -LOG_FILE USA.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat USA.rtf.log 
  errorcount=0
  errorcount=`grep -i error USA.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e BELGIUM.rtf ]; then
  echo ".....Executing XDOLoader for BELGIUM.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINVMAIL_BELGIUM \
  -LANGUAGE en \
  -TERRITORY BE \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME BELGIUM.rtf \
  -LOG_FILE BELGIUM.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat BELGIUM.rtf.log 
  errorcount=0
  errorcount=`grep -i error BELGIUM.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e DENMARK.rtf ]; then
  echo ".....Executing XDOLoader for DENMARK.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINVMAIL_DENMARK \
  -LANGUAGE da \
  -TERRITORY DK \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME DENMARK.rtf \
  -LOG_FILE DENMARK.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat DENMARK.rtf.log 
  errorcount=0
  errorcount=`grep -i error DENMARK.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e FINLAND.rtf ]; then
  echo ".....Executing XDOLoader for FINLAND.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINVMAIL_FINLAND \
  -LANGUAGE fi \
  -TERRITORY FI \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME FINLAND.rtf \
  -LOG_FILE FINLAND.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat FINLAND.rtf.log 
  errorcount=0
  errorcount=`grep -i error FINLAND.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e IRELAND.rtf ]; then
  echo ".....Executing XDOLoader for IRELAND.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINVMAIL_IRELAND \
  -LANGUAGE en \
  -TERRITORY IE \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME IRELAND.rtf \
  -LOG_FILE IRELAND.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat IRELAND.rtf.log 
  errorcount=0
  errorcount=`grep -i error IRELAND.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e NETHERLANDS.rtf ]; then
  echo ".....Executing XDOLoader for NETHERLANDS.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINVMAIL_NETHERLANDS \
  -LANGUAGE nl \
  -TERRITORY NL \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME NETHERLANDS.rtf \
  -LOG_FILE NETHERLANDS.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat NETHERLANDS.rtf.log 
  errorcount=0
  errorcount=`grep -i error NETHERLANDS.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e NORWAY.rtf ]; then
  echo ".....Executing XDOLoader for NORWAY.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINVMAIL_NORWAY \
  -LANGUAGE no \
  -TERRITORY NO \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME NORWAY.rtf \
  -LOG_FILE NORWAY.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat NORWAY.rtf.log 
  errorcount=0
  errorcount=`grep -i error NORWAY.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e SPAIN.rtf ]; then
  echo ".....Executing XDOLoader for SPAIN.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINVMAIL_SPAIN \
  -LANGUAGE es \
  -TERRITORY ES \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME SPAIN.rtf \
  -LOG_FILE SPAIN.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat SPAIN.rtf.log 
  errorcount=0
  errorcount=`grep -i error SPAIN.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e SWEDEN.rtf ]; then
  echo ".....Executing XDOLoader for SWEDEN.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINVMAIL_SWEDEN \
  -LANGUAGE sv \
  -TERRITORY SE \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME SWEDEN.rtf \
  -LOG_FILE SWEDEN.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat SWEDEN.rtf.log 
  errorcount=0
  errorcount=`grep -i error SWEDEN.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e USA.rtf ]; then
  echo ".....Executing XDOLoader for USA.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINVMAIL_USA \
  -LANGUAGE en \
  -TERRITORY US \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME USA.rtf \
  -LOG_FILE USA.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat USA.rtf.log 
  errorcount=0
  errorcount=`grep -i error USA.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e TAIWAN.rtf ]; then
  echo ".....Executing XDOLoader for TAIWAN.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMSINV_TAIWAN \
  -LANGUAGE en \
  -TERRITORY TW \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME TAIWAN.rtf \
  -LOG_FILE TAIWAN.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat TAIWAN.rtf.log 
  errorcount=0
  errorcount=`grep -i error TAIWAN.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e SINGAPORE.rtf ]; then
  echo ".....Executing XDOLoader for SINGAPORE.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMSINVS_SG \
  -LANGUAGE en \
  -TERRITORY SG \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME SINGAPORE.rtf \
  -LOG_FILE SINGAPORE.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat SINGAPORE.rtf.log 
  errorcount=0
  errorcount=`grep -i error SINGAPORE.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e AUSTRIA.rtf ]; then
  echo ".....Executing XDOLoader for AUSTRIA.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINVEULOT_AUSTRIA \
  -LANGUAGE de \
  -TERRITORY AT \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME AUSTRIA.rtf \
  -LOG_FILE AUSTRIA.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat AUSTRIA.rtf.log 
  errorcount=0
  errorcount=`grep -i error AUSTRIA.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e FRANCE.rtf ]; then
  echo ".....Executing XDOLoader for FRANCE.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINVEULOT_FRANCE \
  -LANGUAGE fr \
  -TERRITORY FR \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME FRANCE.rtf \
  -LOG_FILE FRANCE.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat FRANCE.rtf.log 
  errorcount=0
  errorcount=`grep -i error FRANCE.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e GERMANY.rtf ]; then
  echo ".....Executing XDOLoader for GERMANY.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINVEULOT_GERMANY \
  -LANGUAGE en \
  -TERRITORY DE \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME GERMANY.rtf \
  -LOG_FILE GERMANY.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat GERMANY.rtf.log 
  errorcount=0
  errorcount=`grep -i error GERMANY.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e ITALY.rtf ]; then
  echo ".....Executing XDOLoader for ITALY.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINVEULOT_ITALY \
  -LANGUAGE it \
  -TERRITORY IT \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME ITALY.rtf \
  -LOG_FILE ITALY.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat ITALY.rtf.log 
  errorcount=0
  errorcount=`grep -i error ITALY.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e SWITZERLAND.rtf ]; then
  echo ".....Executing XDOLoader for SWITZERLAND.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINVEULOT_SWISS \
  -LANGUAGE de \
  -TERRITORY CH \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME SWITZERLAND.rtf \
  -LOG_FILE SWITZERLAND.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat SWITZERLAND.rtf.log 
  errorcount=0
  errorcount=`grep -i error SWITZERLAND.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e GREECE.rtf ]; then
  echo ".....Executing XDOLoader for GREECE.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINVGR \
  -LANGUAGE en \
  -TERRITORY 00 \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME GREECE.rtf \
  -LOG_FILE GREECE.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat GREECE.rtf.log 
  errorcount=0
  errorcount=`grep -i error GREECE.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e USA.rtf ]; then
  echo ".....Executing XDOLoader for USA.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINV \
  -LANGUAGE en \
  -TERRITORY US \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME USA.rtf \
  -LOG_FILE USA.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat USA.rtf.log 
  errorcount=0
  errorcount=`grep -i error USA.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e IRELAND.rtf ]; then
  echo ".....Executing XDOLoader for IRELAND.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINV \
  -LANGUAGE en \
  -TERRITORY IE \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME IRELAND.rtf \
  -LOG_FILE IRELAND.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat IRELAND.rtf.log 
  errorcount=0
  errorcount=`grep -i error IRELAND.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e NETHERLANDS.rtf ]; then
  echo ".....Executing XDOLoader for NETHERLANDS.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINV \
  -LANGUAGE nl \
  -TERRITORY NL \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME NETHERLANDS.rtf \
  -LOG_FILE NETHERLANDS.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat NETHERLANDS.rtf.log 
  errorcount=0
  errorcount=`grep -i error NETHERLANDS.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e NEWZELAND.rtf ]; then
  echo ".....Executing XDOLoader for NEWZELAND.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINV \
  -LANGUAGE en \
  -TERRITORY NZ \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME NEWZELAND.rtf \
  -LOG_FILE NEWZELAND.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat NEWZELAND.rtf.log 
  errorcount=0
  errorcount=`grep -i error NEWZELAND.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e NORWAY.rtf ]; then
  echo ".....Executing XDOLoader for NORWAY.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINV \
  -LANGUAGE no \
  -TERRITORY NO \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME NORWAY.rtf \
  -LOG_FILE NORWAY.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat NORWAY.rtf.log 
  errorcount=0
  errorcount=`grep -i error NORWAY.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e PORTUGAL.rtf ]; then
  echo ".....Executing XDOLoader for PORTUGAL.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINV \
  -LANGUAGE pt \
  -TERRITORY PT \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME PORTUGAL.rtf \
  -LOG_FILE PORTUGAL.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat PORTUGAL.rtf.log 
  errorcount=0
  errorcount=`grep -i error PORTUGAL.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e SPAIN.rtf ]; then
  echo ".....Executing XDOLoader for SPAIN.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINV \
  -LANGUAGE es \
  -TERRITORY ES \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME SPAIN.rtf \
  -LOG_FILE SPAIN.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat SPAIN.rtf.log 
  errorcount=0
  errorcount=`grep -i error SPAIN.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e SWEDEN.rtf ]; then
  echo ".....Executing XDOLoader for SWEDEN.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINV \
  -LANGUAGE sv \
  -TERRITORY SE \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME SWEDEN.rtf \
  -LOG_FILE SWEDEN.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat SWEDEN.rtf.log 
  errorcount=0
  errorcount=`grep -i error SWEDEN.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e UK.rtf ]; then
  echo ".....Executing XDOLoader for UK.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINV \
  -LANGUAGE en \
  -TERRITORY GB \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME UK.rtf \
  -LOG_FILE UK.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat UK.rtf.log 
  errorcount=0
  errorcount=`grep -i error UK.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e AUSTRALIA.rtf ]; then
  echo ".....Executing XDOLoader for AUSTRALIA.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINV \
  -LANGUAGE en \
  -TERRITORY AU \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME AUSTRALIA.rtf \
  -LOG_FILE AUSTRALIA.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat AUSTRALIA.rtf.log 
  errorcount=0
  errorcount=`grep -i error AUSTRALIA.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e BELGIUM.rtf ]; then
  echo ".....Executing XDOLoader for BELGIUM.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINV \
  -LANGUAGE en \
  -TERRITORY BE \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME BELGIUM.rtf \
  -LOG_FILE BELGIUM.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat BELGIUM.rtf.log 
  errorcount=0
  errorcount=`grep -i error BELGIUM.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e DENMARK.rtf ]; then
  echo ".....Executing XDOLoader for DENMARK.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINV \
  -LANGUAGE da \
  -TERRITORY DK \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME DENMARK.rtf \
  -LOG_FILE DENMARK.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat DENMARK.rtf.log 
  errorcount=0
  errorcount=`grep -i error DENMARK.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e FINLAND.rtf ]; then
  echo ".....Executing XDOLoader for FINLAND.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINV \
  -LANGUAGE fi \
  -TERRITORY FI \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME FINLAND.rtf \
  -LOG_FILE FINLAND.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat FINLAND.rtf.log 
  errorcount=0
  errorcount=`grep -i error FINLAND.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e CANADA.rtf ]; then
  echo ".....Executing XDOLoader for CANADA.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINV \
  -LANGUAGE en \
  -TERRITORY CA \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME CANADA.rtf \
  -LOG_FILE CANADA.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat CANADA.rtf.log 
  errorcount=0
  errorcount=`grep -i error CANADA.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e GERMANY.rtf ]; then
  echo ".....Executing XDOLoader for GERMANY.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINV \
  -LANGUAGE de \
  -TERRITORY DE \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME GERMANY.rtf \
  -LOG_FILE GERMANY.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat GERMANY.rtf.log 
  errorcount=0
  errorcount=`grep -i error GERMANY.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e FRANCE.rtf ]; then
  echo ".....Executing XDOLoader for FRANCE.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINV \
  -LANGUAGE fr \
  -TERRITORY FR \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME FRANCE.rtf \
  -LOG_FILE FRANCE.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat FRANCE.rtf.log 
  errorcount=0
  errorcount=`grep -i error FRANCE.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e SWITZERLAND.rtf ]; then
  echo ".....Executing XDOLoader for SWITZERLAND.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINV \
  -LANGUAGE de \
  -TERRITORY CH \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME SWITZERLAND.rtf \
  -LOG_FILE SWITZERLAND.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat SWITZERLAND.rtf.log 
  errorcount=0
  errorcount=`grep -i error SWITZERLAND.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e AUSTRIA.rtf ]; then
  echo ".....Executing XDOLoader for AUSTRIA.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINV \
  -LANGUAGE de \
  -TERRITORY AT \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME AUSTRIA.rtf \
  -LOG_FILE AUSTRIA.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat AUSTRIA.rtf.log 
  errorcount=0
  errorcount=`grep -i error AUSTRIA.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e ITALY.rtf ]; then
  echo ".....Executing XDOLoader for ITALY.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINV \
  -LANGUAGE it \
  -TERRITORY IT \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME ITALY.rtf \
  -LOG_FILE ITALY.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat ITALY.rtf.log 
  errorcount=0
  errorcount=`grep -i error ITALY.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e SPAIN.rtf ]; then
  echo ".....Executing XDOLoader for SPAIN.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINV \
  -LANGUAGE es \
  -TERRITORY ES \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME SPAIN.rtf \
  -LOG_FILE SPAIN.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat SPAIN.rtf.log 
  errorcount=0
  errorcount=`grep -i error SPAIN.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e SWEDEN.rtf ]; then
  echo ".....Executing XDOLoader for SWEDEN.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINV \
  -LANGUAGE sv \
  -TERRITORY SE \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME SWEDEN.rtf \
  -LOG_FILE SWEDEN.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat SWEDEN.rtf.log 
  errorcount=0
  errorcount=`grep -i error SWEDEN.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e XXGIL_EMAIL_COMM_INVOICE_PKG.pkb ]; then
  dos2unix XXGIL_EMAIL_COMM_INVOICE_PKG.pkb
  echo ".....Compiling XXGIL_EMAIL_COMM_INVOICE_PKG.pkb"
  cp -f XXGIL_EMAIL_COMM_INVOICE_PKG.pkb $XXGIL_TOP/sql/
  chmod 755 $XXGIL_TOP/sql/XXGIL_EMAIL_COMM_INVOICE_PKG.pkb
  COPY_TO_DMZ  XXGIL_EMAIL_COMM_INVOICE_PKG.pkb $XXGIL_TOP/sql/
  sqlplus -s  $APPSID @XXGIL_EMAIL_COMM_INVOICE_PKG.pkb > XXGIL_EMAIL_COMM_INVOICE_PKG.pkb.log 2> XXGIL_EMAIL_COMM_INVOICE_PKG.pkb.log
  errorcount=0
  errorcount=`grep -i error XXGIL_EMAIL_COMM_INVOICE_PKG.pkb.log | grep -icv "No errors" | wc -l `
  cat XXGIL_EMAIL_COMM_INVOICE_PKG.pkb.log
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e PORTUGAL_PRINT.rtf ]; then
  echo ".....Executing XDOLoader for PORTUGAL_PRINT.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINVPT \
  -LANGUAGE pt \
  -TERRITORY PT \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME PORTUGAL_PRINT.rtf \
  -LOG_FILE PORTUGAL_PRINT.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat PORTUGAL_PRINT.rtf.log 
  errorcount=0
  errorcount=`grep -i error PORTUGAL_PRINT.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e GERMANY.rtf ]; then
  echo ".....Executing XDOLoader for GERMANY.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINVLOTSPLIT_GERMANY \
  -LANGUAGE en \
  -TERRITORY DE \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME GERMANY.rtf \
  -LOG_FILE GERMANY.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat GERMANY.rtf.log 
  errorcount=0
  errorcount=`grep -i error GERMANY.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e GERMANY.rtf ]; then
  echo ".....Executing XDOLoader for GERMANY.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINVSPLIT \
  -LANGUAGE de \
  -TERRITORY DE \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME GERMANY.rtf \
  -LOG_FILE GERMANY.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat GERMANY.rtf.log 
  errorcount=0
  errorcount=`grep -i error GERMANY.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e AUSTRIA.rtf ]; then
  echo ".....Executing XDOLoader for AUSTRIA.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINVSPLIT \
  -LANGUAGE de \
  -TERRITORY AT \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME AUSTRIA.rtf \
  -LOG_FILE AUSTRIA.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat AUSTRIA.rtf.log 
  errorcount=0
  errorcount=`grep -i error AUSTRIA.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e SWITZERLAND.rtf ]; then
  echo ".....Executing XDOLoader for SWITZERLAND.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINVSPLIT \
  -LANGUAGE de \
  -TERRITORY CH \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME SWITZERLAND.rtf \
  -LOG_FILE SWITZERLAND.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat SWITZERLAND.rtf.log 
  errorcount=0
  errorcount=`grep -i error SWITZERLAND.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e FRANCE.rtf ]; then
  echo ".....Executing XDOLoader for FRANCE.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINVSPLIT \
  -LANGUAGE fr \
  -TERRITORY FR \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME FRANCE.rtf \
  -LOG_FILE FRANCE.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat FRANCE.rtf.log 
  errorcount=0
  errorcount=`grep -i error FRANCE.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ -e ITALY.rtf ]; then
  echo ".....Executing XDOLoader for ITALY.rtf"
  java oracle.apps.xdo.oa.util.XDOLoader UPLOAD \
  -DB_USERNAME ${apps_user} \
  -DB_PASSWORD ${apps_pwd} \
  -JDBC_CONNECTION ${TNS_STRING} \
  -LOB_TYPE TEMPLATE_SOURCE \
  -APPS_SHORT_NAME XXGIL \
  -LOB_CODE XXGILARCOMINVSPLIT \
  -LANGUAGE it \
  -TERRITORY IT \
  -XDO_FILE_TYPE RTF \
  -NLS_LANG ${NLS_LANG} \
  -FILE_CONTENT_TYPE 'application/rtf' \
  -FILE_NAME ITALY.rtf \
  -LOG_FILE ITALY.rtf.log \
  -CUSTOM_MODE FORCE 
  FIN_STATUS=$?
  echo ${FIN_STATUS}
  cat ITALY.rtf.log 
  errorcount=0
  errorcount=`grep -i error ITALY.rtf.log | wc -l`
  if [ "$errorcount" -ge 1 ]
  then 
    migrErrorCode=1
  fi
fi
if [ "$migrErrorCode" = "1" ]
then 
  FCP_BODY="[ATTENTION]:Migration Failed. See log files for details."
  STATUS=FAILED
else 
  FCP_BODY="Though the tool did not capture any errors please validate the log files for each of your code component."
  STATUS=SUCCESS
fi
echo ${FCP_BODY}
tar -cvf ROTC85_122_Migrations.log.tar *.log
FCP_EMAIL_SUBJECT=MIGRATION:ROTC85_122:${TWO_TASK}::${STATUS}
FCP_RECIPIENTS="${MAIL_DIST_LIST};vaibhav.hadawale1@gilead.com"
  echo  "# Sending email***#"
ATTACH_FILENAME=ROTC85_122_Migrations.log.tar
mutt -s ${FCP_EMAIL_SUBJECT} ${FCP_RECIPIENTS} -a ${ATTACH_FILENAME} << TT
${FCP_BODY}
TT
echo "<TR><TD>${TWO_TASK}</TD>  <TD >`date`</TD><TD>ROTC85_122</TD>  <TD>${STATUS}</TD> <TD>${FCP_RECIPIENTS}</TD></TR>" >> ${OA_HTML}/migrations.log
echo ""
echo "Process Ended at `date +%d/%m/%y.%H:%M:%S`"
echo "-------------------[End of Installation]-------------------"
}
# *******************************************************************
#  Script starts here
# *******************************************************************
MAIN 2>&1 | tee -a $INSTALLATION_LOGFILE
FCP_EMAIL_SUBJECT=InstallScriptLog:ROTC85
FCP_RECIPIENTS="${MAIL_DIST_LIST};vaibhav.hadawale1@gilead.com"
echo  "# Sending email for installation log***#"
mutt -s ${FCP_EMAIL_SUBJECT} ${FCP_RECIPIENTS} -a ${INSTALLATION_LOGFILE} << TT
The attached file is the installation shell script log.
TT
echo "Installation logfile: $INSTALLATION_LOGFILE "
echo "-------------------[End of Script]-------------------"
